### ISSUE TITLE
Push API

### ISSUE THREAD

**Issue by spradlig** [s4w3d0ff/python-poloniex#9]
I have been attempting to get the Push API example to work. To be fair, I'm using Python 2.7 and 3.5. (Both are from Anaconda which comes with a bunch scientific tools already installed as well.) I am trying on Windows 7 & 10 as well as Ubuntu 14.04.

All of the Windows + Python 3.5 attempts fail with the error: 'ImportError: cannot import name '_win32stdio''.

The Ubuntu 14.04 with Python 2.7 returns another ImportError from twisted for 'optionsForClientTLS' for the TrollBox example and 'ReactorNotRestartable' for the ticker example. Additionally, on my 2.7 machine I need to remove the import poloniex line and TICKER initialization (replaced by {}). Poloniex installed without error but Spyder refused to import it. Given that I thought I could still use the code with the modifications listed I didn't get hung up on getting the poloniex package to import.

I can't remember off the top of my head what the Ubuntu 14.04 with Python 3.5 or the Windows 10 with Python 2.7 failed on but they failed or I'd be using one of them.

I'd really like to get the Push API for the ticker working in Python 3.5 and dumping the data to memcache. But I can't get the example to work on any of my machines. Any suggestions?

**Comment by s4w3d0ff** [comment]
I had lots of issues trying to get the autobaun/twisted working on my Ubuntu 14.04 based system (I use Peppermint 6 for development).

I have not, but you could try asyncio instead of twisted:
`pip install autobahn[asyncio]`

According to [install docs](http://autobahn.ws/python/installation.html), Asyncio comes bundled with Python 3.4+ so maybe it is more compatible.

I did have to do a lot of google searching to get the right dependencies. Perhaps you need the `python-dev` package installed, I seem to remember having to install it. Sorry I can't be more help.

`ImportError: cannot import name '_win32stdio'` looks like a 'system' dependency header (rather than an actual python module) but I don't use windows much so I wouldn't know off hand.

As for running the ticker example:
You would need to have the poloniex module already installed before running in order to populate the initial TICKER dict on start up. Else you would have to wait for a market to make a trade in order to create a new entry in the dict for that market.

**Comment by s4w3d0ff** [comment]
I'm creating a VM so I can document how to get the correct dependencies for Ubuntu 14.04

**Comment by s4w3d0ff** [comment]
From fresh 14.04 install setup for python 2.7:
```bash
sudo apt-get install build-essential libssl-dev python-pip python-dev libffi-dev git
sudo pip install pyOpenSSL
sudo pip install autobahn[twisted]
sudo pip install service_identity
sudo apt-get update
sudo apt-get upgrade
git clone https://github.com/s4w3d0ff/python-poloniex.git
cd python-poloniex
sudo python setup install
cd examples
python polocalbox.py
python tickercatcher.py
```
Should be similar for Python 3 (using `pip3` and `python3` commands)

**Comment by spradlig** [comment]
On Mon, Jun 13, 2016 at 9:17 PM, s4w3d0ff <notifications@github.com> wrote:

> python polocalbox.py


Thanks for the quick response. I tried your instructions using VirtualBox
with GuestAdditions for the VM (Ubuntu 64 bit Desktop). No joy. I've
attached a screenshot. I'm installing Ubuntu 14.04 32 bit desktop now to
see if that fixes anything.

Thanks again,
Gabe

**Comment by s4w3d0ff** [comment]
If you can post some of the errors along the way I might be able to help if I recognize the error, I can't see the screen shot.

**Comment by spradlig** [comment]
Both the 64 bit ad 32 bit Ubuntus fail on the optionsForClientTLS error
which happens when I attempt to fire off the trollbox or ticker examples.

Here's the trace from 32 bit, ticker example:
2016-06-14 13:00:33-0600 [-] Log opened.
2016-06-14 13:00:33-0600 [-] Traceback (most recent call last):
2016-06-14 13:00:33-0600 [-]   File "tickercatcher.py", line 35, in <module>
2016-06-14 13:00:33-0600 [-]     subscriber.run(Subscribe2Ticker)
2016-06-14 13:00:33-0600 [-]   File
"/usr/local/lib/python2.7/dist-packages/autobahn/twisted/wamp.py", line
199, in run
2016-06-14 13:00:33-0600 [-]     from twisted.internet.ssl import
optionsForClientTLS
2016-06-14 13:00:33-0600 [-] ImportError: cannot import name
optionsForClientTLS

Thanks,
Gabe

**Comment by s4w3d0ff** [comment]
That seems like a ssl error:
From: https://twistedmatrix.com/documents/14.0.0/core/howto/ssl.html
Using TLS in Twisted requires that you have pyOpenSSL installed. A quick test to verify that you do is to run from OpenSSL import SSL at a python prompt and not get an error.

Perhaps you don't have the latest version of ssl.

Try installing the Ubuntu packages:
```bash
sudo apt-get install build-essential libssl-dev python-pip python-dev libffi-dev git
```
THEN update and upgrade (hopefully this will upgrade ssl libraries if needed): 
```bash
sudo apt-get update && sudo apt-get upgrade
```
Install the pip dependencies:
```bash
sudo pip install pyOpenSSL
sudo pip install service_identity
sudo pip install autobahn[twisted]
```
Clone and install the polo repo:
```bash
git clone https://github.com/s4w3d0ff/python-poloniex.git
cd python-poloniex
sudo python setup install
```
Try the example:
```bash
python examples/polocalbox.py
```

Sometimes pip will 'install' a module but will fail installing the modules dependencies leaving a broken module on the system (for example if you try to install autobahn[twisted] without the proper ssl libs the module will fail on install but still claim to be installed). The way I save on headaches is by uninstalling the broken module, installing the dependency manually then trying the original install again (looking for new errors and repeating if necessary). Hopefully this helps.

**Comment by s4w3d0ff** [comment]
woop did not mean to close

**Comment by spradlig** [comment]
Well, now that you mention it... When I was following your instructions
line by line (before providing the log/trace) and tried to install
pyOpenSSL, I was informed by pip/OS that it was already installed.

After your latest comments, I tried to uninstall it and can't - "Not
uninstalling pyOpenSSL at /usr/lib/python2.7/dist-packages, owned by OS". I
have also, unsuccessfully, attempted to upgrade pyOpenSSL.

So... I tried several things. The first thing that appears to have worked -
for the trollbox - is to follow all of your instructions but for a 32 bit
server rather desktop edition of Ubuntu 14.04. However, there are a couple
of tweaks I made prior to trying the trollbox...
1) I upgraded the pyOpenSSL using 'sudo pip install pyOpenSSL --upgrade'.
(Which I could not get to work on the desktop versions - neither 32 or 64
bit.)
2) I install twisted before autobahn in 2 separate commands rather than
using autobahn[twisted].

Not sure either was required but that's what I did and trollbox is posting
to my screen. By the time I finished this I also tested the ticker and the
ticker.json file has been created and populated with what looks like the
correct data. Whether it is accurate or not I don't know but I assume it is.

Thanks for all the help,
Gabe

**Comment by s4w3d0ff** [comment]
Awesome, glad things worked out, I will continue to poke around and try to find a clean solution. 

As I said before, perhaps this whole mess can be avoided if using asyncio instead of twisted for Python 3 (or maybe even 2). You would have to change the `import` and the `@inlinecallback` lines of the examples to run them using asyncio.

I'll update the examples README.md as I search for the correct formula.

**Comment by spradlig** [comment]
Good to hear. I'll look into it a little as well but I've never worked with
websockets before. This little project has already taken longer than I'd
hoped so I need to move on to the final goal and then come back to this.

Again, thanks for all the time and the quick response.

**Comment by s4w3d0ff** [comment]
Did more testing and updated the [README.md](https://github.com/s4w3d0ff/python-poloniex/blob/master/examples/README.md) in the examples folder. Basically the same as before just less steps. pyOpenSSL doesn't "_need_" to be upgraded (just the underlying ssl packages) but it is recommended. Hopefully this clears things up.

See Commit: https://github.com/s4w3d0ff/python-poloniex/commit/af650c17d13d246b52d199e24d218261c403dd1d
