### ISSUE TITLE
AttributeError: 'Coach' object has no attribute 'semaphore'

### ISSUE THREAD

**Issue by t0neg** [s4w3d0ff/python-poloniex#83]
Hello,

Fresh virtualenv install `pip install git+https://github.com/s4w3d0ff/python-poloniex.git`
Python Version: `Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32`
Simple test:
```python
from poloniex import Poloniex
polo = Poloniex()
print(polo.returnTicker()['BTC_ETH'])
```
Error stack:
```
Traceback (most recent call last):
  File "D:/python_tutorials/poloniex_project/poloniex_api/polo_test.py", line 7, in <module>
    pprint(polo.returnTicker()['BTC_ETH'])
  File "D:\python_tutorials\poloniex_project\venv\lib\site-packages\poloniex\__init__.py", line 201, in returnTicker
    return self.__call__('returnTicker')
  File "D:\python_tutorials\poloniex_project\venv\lib\site-packages\poloniex\__init__.py", line 139, in __call__
    self.coach.wait()
  File "D:\python_tutorials\poloniex_project\venv\lib\site-packages\poloniex\coach.py", line 44, in wait
    self.semaphore.acquire()  # blocking call
AttributeError: 'Coach' object has no attribute 'semaphore'
```

Caused by commit 7d60109c5c5d95e85a7f69f3e7bd7804c5c69460
commented line 39:
```python
        #self.semaphore = Semaphore(callLimit)
```

**Comment by s4w3d0ff** [comment]
thank you!
